### ISSUE TITLE
Call for colaboration

### ISSUE THREAD

**Issue by WukongsCommand** [DragoniteSpam/PokemonDoOrDie#1]
Hello! I just found out this repo and wanted to tell I'm working in a very, very similar project (writing a Pokémon engine using GMS and based on Essentials). I'm interested in collaborating with you, could you please drop an e-mail address?

**Comment by DragoniteSpam** [comment]
There are like two things (ai and bug hunting) I want to finish up before I do an "0.0.0.1" release and start actively talking to people about it, which should hopefully only take me a few days maybe? After that, sure! If you don't hear from me again by Saturday or Sunday you should probably bother me again, because that would probably mean I've already forgotten.

I don't really want to leave my email in a public Github thread though, do you have a Twitter account or somewhere I could message you?

Anyway . . . do you have more information about your project right now, or are you just getting started?

**Comment by WukongsCommand** [comment]
I've been working on my project for ~1 year and a half. I have an overworld system with map transitions and NPCs working, a HUD, a working item system, evolution and move learning systems, and 2 battle systems (a legacy one and a refactored one currently in the making). I'll attach some screenshots.
https://my.mixtape.moe/pbqemv.png
https://my.mixtape.moe/ncwvdu.png
https://my.mixtape.moe/jtgwxd.jpg
https://my.mixtape.moe/lsiglq.jpg
https://my.mixtape.moe/ehmqbb.mp4

I don't really have public profiles anywhere. Do you have a GitLab account? I can give you access to the repository. I'm going to release it as free software, but I haven't made the repo public yet.

**Comment by DragoniteSpam** [comment]
Hmm, so yours looks quite different from what I've been working towards. Most notably, it's 2D, and I want to at least optionally allow 3D (as my battle system already is).

Probably worth pointing out - I thought it was in the readme, but I guess I forgot, so I'll add it later - I don't *just* want this to be "Essentials for Game Maker," but a turn-based battle system that you could use for just about anything: Pokémon, Dragon Quest, EBF, probably Final Fantasy, whatever. I just want it to be similar enough to Essentials/RPG Maker out of the box that people aren't totally confused about how it works.

Anyway, my Gitlab account is just [a clone of this one](https://gitlab.com/DragoniteSpam), although for now I'd rather keep working on this and you seem far enough along that I don't want to distract you from it :P

**Comment by WukongsCommand** [comment]
I see. Good luck with your project!

**Comment by DragoniteSpam** [comment]
Do let me know how it goes, though. I want to see how other people approach this kind of thing.

**Comment by WukongsCommand** [comment]
You should've received access to the repo. Make a issue if you have any questions or want to know how something works. You can also check the docs.

**Comment by DragoniteSpam** [comment]
Got the invite, will have to remember to play with it more later.

(Is there a way to clone and mess with the code, or do I not have the permissions to do that? I'm not really familiar with how Gitlab works.)

**Comment by WukongsCommand** [comment]
Yes, you should be able to clone the repository or manually download it through the web interface. For more information, check the `BUILDING.md` file.

**Comment by DragoniteSpam** [comment]
I'm not actually able to view the code or anything, the "project" page just has `Pokémon engine developed with Game Maker: Studio 1.4` and the project ID and that's about it.

**Comment by WukongsCommand** [comment]
Seems like I didn't gave you enough permissions before, try checking it again.

**Comment by DragoniteSpam** [comment]
It's there now. Thanks!
